# Generated by Django 4.2.7 on 2025-06-15 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2, unique=True)),
                ('country_name', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=3)),
                ('flag', models.CharField(max_length=10)),
                ('supported_methods', models.JSONField(default=list)),
                ('banks', models.JSONField(default=list)),
                ('mobile_money_providers', models.JSONField(default=list)),
                ('ussd_codes', models.JSONField(default=dict)),
                ('min_amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar'), ('GHS', 'Ghanaian Cedi'), ('ZAR', 'South African Rand'), ('KES', 'Kenyan Shilling'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('XOF', 'West African CFA Franc'), ('EGP', 'Egyptian Pound')], default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('ussd', 'USSD'), ('qr', 'QR Code'), ('eft', 'EFT')], max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_country', models.CharField(default='NG', max_length=2)),
                ('mobile_money_provider', models.CharField(blank=True, max_length=50)),
                ('mobile_money_number', models.CharField(blank=True, max_length=20)),
                ('bank_code', models.CharField(blank=True, max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('paystack_reference', models.CharField(blank=True, max_length=100)),
                ('authorization_code', models.CharField(blank=True, max_length=100)),
                ('gateway_response', models.TextField(blank=True)),
                ('channel', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('charge.success', 'Charge Success'), ('charge.failed', 'Charge Failed'), ('transfer.success', 'Transfer Success'), ('transfer.failed', 'Transfer Failed')], max_length=50)),
                ('paystack_event_id', models.CharField(max_length=100, unique=True)),
                ('reference', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('raw_data', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
